CREATE TABLE events(
    region_abbr   varchar(5),
    postal_code   varchar(10),
    latitude      numeric(19,6),
    id            varchar(50),
    city_name     varchar(50),
    longitude     numeric(19,6),
    country_name  varchar(50),
    country_abbr  varchar(50),
    region_name   varchar(50),
    start_time    datetime,
    title         varchar(255),
    venue_address varchar(255),
    venue_id      varchar(50),
    stop_time     datetime,
    venue_name    varchar(255))